// Generated by CoffeeScript 1.8.0
(function() {
  var runner;

  runner = function() {
    var interval, livereload, opts, path, port, resolve, server;
    livereload = require('./livereload');
    resolve = require('path').resolve;
    opts = require('opts');
    opts.parse([
      {
        short: "p",
        long: "port",
        description: "Specify the port",
        value: true,
        required: false
      }, {
        short: "i",
        long: "interval",
        description: "Specify the interval",
        value: true,
        required: false
      }
    ].reverse(), true);
    port = opts.get('port') || 35729;
    interval = opts.get('interval') || 1000;
    server = livereload.createServer({
      port: port,
      interval: interval,
      debug: true
    });
    path = resolve(process.argv[2] || '.');
    console.log("启动LiveReload成功,监控地址:" + path + " 端口:" + port + ".");
    server.watch(path);
    return;
  };

  module.exports = {
    run: runner
  };

}).call(this);
